### ISSUE TITLE
Only marked packets are routed. (Fix included)

### ISSUE THREAD

**Issue by cmspam** [fakemanhk/openwrt-jp-ipoe#11]
I noticed a potential issue with my map.sh file that I provided before.

Only packets that are marked are routed. It's possible the mark is modified or lost somehow, and this packet will not be routed. 

Although I can't figure out the reason why, I have found such packets every so often in my usage, where the mark is not set or was changed by something else, and these packets do not get routed.

I made a modification to map.sh to route unmarked packets through the last portset. Although it would be more ideal to get to the root cause of why the marks are not set or picked up correctly in some cases, this will at least provide a safety net, and there won't be unrouted packets.

I also implemented TCP and UDP along with ICMP in native nft commands, because it makes it cleaner.

See attached for latest version (March 4, 2023)
[map.sh.txt](https://github.com/fakemanhk/openwrt-jp-ipoe/files/10888364/map.sh.txt)

**Comment by TimOfAllTrades** [comment]
So far this has been the best map.sh implementation.  Previously suumo.jp was another site that was very intermittent due to the port issue.  This fixed it.

**Comment by fakemanhk** [comment]
> So far this has been the best map.sh implementation. Previously suumo.jp was another site that was very intermittent when you tried to view the property listings in the map API, due to the port issue. This fixed it. Thanks

Um....when you mentioned suumo.jp website I do noticed some weird loading behaviors which I couldn't explain well (it happens only on desktop  page view but not mobile view)

**Comment by fakemanhk** [comment]
Closing this one since we have found another issue based on this
