### ISSUE TITLE
CRLF in map.sh vs LF

### ISSUE THREAD

**Issue by TimOfAllTrades** [fakemanhk/openwrt-jp-ipoe#14]
I don't know if I am getting this right, but when I download the map.sh file, it appears to contain CRLF line breaks.  At least on my router, it seems only LF can be used and CRLF line breaks will cause an error.  Is it worth mentioning?

Also a footnote for less smart people like me, maybe mention flip the execute bit is chmod 755 (to be the same as the other files I guess).

**Comment by fakemanhk** [comment]
That's strange, I can take a look on the file later.

But for execute bit issue, I did mention it after the diff content (just not the exact command), probably I should have made it more clear, let me verify with the file and update together.

**Comment by fakemanhk** [comment]
Does it work if you use this [direct link](https://raw.githubusercontent.com/fakemanhk/openwrt-jp-ipoe/main/map.sh.new) to download?

**Comment by TimOfAllTrades** [comment]
It was the same, but you know what, it is probably just my own notepad++ acting wierd.  Go ahead and disregard this.  Thanks for your effort.
