### ISSUE TITLE
Could you share your /etc/config/network?

### ISSUE THREAD

**Issue by alexisfrjp** [fakemanhk/openwrt-jp-ipoe#16]
Hey, could you share your `/etc/config/network` file?

You assumed we already have access to Luci and all the interfaces exist already but it isn't the case.
After creating the WAN6 interface, I don't get an IPv6 address... only the IPv6-PD.

```
config interface 'wan6'
        option proto 'dhcpv6'
        option device 'eth2'
        option ip6prefix '2400:XXXX:XXXX:XXXX::/56'
        option reqaddress 'try'
        option reqprefix 'auto'
```

I wonder what I need to setup, everything by default in Luci.

Thank you!

**Comment by fakemanhk** [comment]
Mine is more or less same as yours, however I have no Hikari Denwa so I only have a /64 prefix, you have /56 which looks different, what's your plan and provider?
Anything suspicious in System Logs regarding your eth2?

**Comment by alexisfrjp** [comment]
I also tried to spoof the wan's mac address of the NTT XG-100NE router just in case there is any protection.
My plan is NTT Hikari Cross (10G) wth ぷらら as the ISP. Maybe there is something more needed if the prefix is <64.

Nothing special in the System Logs, I'll check again, thank you!

**Comment by fakemanhk** [comment]
If I am not wrong, [here](https://www.plala.or.jp/option/gggg/spec/index.html) seems showing ぷらら 10G is using transix/ds-lite??

**Comment by alexisfrjp** [comment]
Looks like the NTT router doesn't have an ip address for its WAN, then it's fine. 
I was able to get an IP for the LAN.

It's definitely map-e, I have the XG-100N not PR500* modem, and I got all the information from the NTT router.

**Comment by alexisfrjp** [comment]
I'm very new in the IPv6 world.
ISP definitely assumes I have the proper equipment and provide their NTT router anyway that is way too basic, can't even add static routes... that's why I'm trying to get rid of it.
Thanks for your help!

**Comment by fakemanhk** [comment]
> ISP definitely assumes I have the proper equipment

Because they've given at least one to you already :) Basic or not is not really their concern, as long as it's "just work".

We are already a lot better than those using SoftBank, from what I know their 4-over-6 implementation is based on something similar to 4rd which is kind of legacy.

**Comment by prijkes** [comment]
This is the WAN6 interface setting when I used Hikari Cross (NTT+PLALA+XG-100N+MAP-E)):

config interface 'WAN6_MAPE'
        option proto 'map'
        option offset '6'
        option ipaddr '153.252.240.0'
        option ip4prefixlen '20'
        option ip6prefixlen '38'
        option psidlen '6'
        option ealen '18'
        option encaplimit 'ignore'
        option tunlink 'wan6'
        option ip6prefix '2400:4150:7c00::'
        option peeraddr '2001:380:a120::9'
        option mtu '9014'

Note that I named the interface WAN6_MAPE instead of WAN6.

**Comment by fakemanhk** [comment]
> ISP definitely assumes I have the proper equipment and provide their NTT router anyway that is way too basic, can't even add static routes... that's why I'm trying to get rid of it.

So now I noticed the setting in OpenWrt WAN6 interface, from the drop down list you should probably choose "disable" to stop it from requesting address, and it will go straight to get the prefix from CPE only

![Screenshot 2023-04-02 16 42 56](https://user-images.githubusercontent.com/21307353/229340756-ca8bfb68-0f84-4414-961d-42613fe22254.png)

**Comment by alexisfrjp** [comment]
Thanks! I was able to have it working following a youtube video. I didn't need to have any hard coded prefix or values in the config files, it just worked.
The WAN didn't need to have an IP address (it doesn't do NAT anyway).

Thanks all!

Softbank deserves to go bankrupt if they support proprietary protocols.

**Comment by fakemanhk** [comment]
> Thanks! I was able to have it working following a youtube video. I didn't need to have any hard coded prefix or values in the config files, it just worked. The WAN didn't need to have an IP address (it doesn't do NAT anyway).
> 
> Thanks all!
> 
> Softbank deserves to go bankrupt if they support proprietary protocols.

I saw that you have /56 prefix assigned by ISP, actually this is a good sign that you have much less trouble on IPv6 setup because as what I stated in "problem" part is the "/64 prefix" which causes headache. But MAP-E of course is another big trouble.

SoftBank technically is not using proprietary protocol, it's just a kind of faded out implementation and keep using it as is, I know that someone had written an add-on script for OpenWrt 18.x to use it, just unsure if it still works now :p 

There will be upcoming 23.x release, I hope this MAP-E fix survives that update...

**Comment by alexisfrjp** [comment]
I think that's the least acceptable for a 10G connexion.
Don't worry, only OpenWrt changes, not the map-e protocol. If needed we will change the script ;) the joy of open-source.

**Comment by fakemanhk** [comment]
> Don't worry, only OpenWrt changes, not the map-e protocol. If needed we will change the script ;) the joy of open-source.

This is my original intention to write this thing, I know things can be improved but I might not have all the knowledge/time into it, I'm glad that I had made a good start and now there is some more observable improvements.

For your case I will update my page again to indicate the difference to others so that they won't worry about the WAN6 assignment.

**Comment by alexisfrjp** [comment]
So was I but I found you first ;) thanks!
And actually we should push the updated script to the OpenWrt repo.

**Comment by fakemanhk** [comment]
Currently I do not have enough information about the MAP-E/MAP-T implementation in other countries, from my previous search I saw some ISPs in EU has MAP-E/MAP-T as well, but I don't know if they do the same thing so I am hesitating on pushing this to official repo. If we can find some users there to test it would be great.

**Comment by alexisfrjp** [comment]
We still can add a special interface type for Japan if the implementation changes depending on the country...

**Comment by cre8ivejp** [comment]
> Thanks! I was able to have it working following a youtube video. I didn't need to have any hard coded prefix or values in the config files, it just worked. The WAN didn't need to have an IP address (it doesn't do NAT anyway).
> 
> Thanks all!
> 
> Softbank deserves to go bankrupt if they support proprietary protocols.

@alexisfrjp, hi.

Is it possible for you to share the YouTube video?
I also have /56 ipv6 prefix, and it only shows the IPV6-PD in the WAN6.
You mentioned that the WAN doesn't need to get the IP address, and it worked. Did you configure everything as described in the README?
If you could share the video or your settings, I would greatly appreciate any help.

I'm using the 10G V6 Plus plan from En Hikari (enひかり). Router NTT XG-100NE.
OpenWRT 23.05.

**Comment by alexisfrjp** [comment]
I spent time reading and trying.
From my history, here are the 2 youtube videos I've watched at that time. I believe they helped me understanding IPv6 with openwrt.

* https://www.youtube.com/watch?v=LJPXz8eA3b8
* https://www.youtube.com/watch?v=jlG_nrCOmJc&t=889s

As for the config file, I can't find it anymore (in the end we use the existing NTT router with the special page for port forwarding).

Hope it helps! Good luck!

For reference, here are the links I stored for the future (can be relevant or not)
* https://github.com/marcelocf/linux-map-e-ocn
* https://forum.openwrt.org/t/a-guide-for-japan-ntt-users-on-ipoe-ipv6-setting-map-e-only/150587
* https://forum.openwrt.org/t/typical-example-using-ipv6-pd-from-isp/155897

**Comment by cre8ivejp** [comment]
> I spent time reading and trying. From my history, here are the 2 youtube videos I've watched at that time. I believe they helped me understanding IPv6 with openwrt.
> 
> * https://www.youtube.com/watch?v=LJPXz8eA3b8
> * https://www.youtube.com/watch?v=jlG_nrCOmJc&t=889s
> 
> As for the config file, I can't find it anymore (in the end we use the existing NTT router with the special page for port forwarding).
> 
> Hope it helps! Good luck!
> 
> For reference, here are the links I stored for the future (can be relevant or not)
> 
> * https://github.com/marcelocf/linux-map-e-ocn
> * https://forum.openwrt.org/t/a-guide-for-japan-ntt-users-on-ipoe-ipv6-setting-map-e-only/150587
> * https://forum.openwrt.org/t/typical-example-using-ipv6-pd-from-isp/155897

Thank you so much!

His videos are the best. I have been watching it to configure the VLANs and the Firewall.
One of the reasons that I wanted to switch to OpenWRT is the port forwarding because the NTT router doesn't support it. I didn't know about that special page. Where did you find it? Is there any website talking about it?

**Comment by alexisfrjp** [comment]
`http://192.168.123.1/t/` oviously, change the IP.

![image](https://github.com/fakemanhk/openwrt-jp-ipoe/assets/6713988/8c582e53-9c30-4b9a-88f1-1495e51a6f21)

![image](https://github.com/fakemanhk/openwrt-jp-ipoe/assets/6713988/e94d911e-3a17-413e-a265-79b429f0c830)

It'll give you the list of ports you can use.

**Comment by cre8ivejp** [comment]
Awesome!
Thank you!

**Comment by cre8ivejp** [comment]
Mine is not showing the option. It says `1 block` though. But you can't click on it.
I'm using the latest firmware version 04.00.0002.
I will take a look deeper after work.

![Screenshot 2024-01-22 at 11 38 11 AM](https://github.com/fakemanhk/openwrt-jp-ipoe/assets/2486691/4c91b3e8-1597-4c72-afae-351f9949bf97)

**Comment by alexisfrjp** [comment]
You can't click on it? here is the link `http://192.168.123.1/fj/com.ntt.mape/mape/index.html`

**Comment by cre8ivejp** [comment]
@alexisfrjp, thanks for sharing the link.
I tried to access it while logged in, but it says the page doesn't exist, 404. So I gave up.

But, after watching the videos you suggested, everything became clear, and I could make it work using the correct settings for my case.
Once again, thank you so much!

**Comment by alexisfrjp** [comment]
Too bad, they might have blocked it for newer version... Good to know!

**Comment by fakemanhk** [comment]
> Too bad, they might have blocked it for newer version... Good to know!

I'm not surprised, just like the SO-NET one, initially you have some way to hack into it to enable bridge mode to use your own router, then they pushed new firmware which closed the loophole.
