### ISSUE TITLE
Multiple port forwarding on MAP-E with global static IPv4

### ISSUE THREAD

**Issue by advanpix** [fakemanhk/openwrt-jp-ipoe#18]
Thank you very much for your work. I read your posts on reddit and openwrt forum and decided to contact you, in a hope you might help me with advice.

My contract with ISP includes フレッツ 光クロス 10G line + v6plus (MAP-E) + global static IPv4. In theory, global static IPv4 allows me to use all ports 0-65535. This is exactly what I need for my use case. In more detail, router must be able to open/forward ports in ranges. For example, open/forward ports 40000-40499 (500 ports in total) to local IP address.

Surprisingly I cannot find any router which allows this! Mandatory NTT router supplied by ISP (XG-100NE) can open/forward only 64 ports in total. All other routers I checked (NEC, Buffalo, etc.) also have this restriction - only limited number of ports can be forwarded (with one-by-one setting through UI - painful).

By any chance, do you know any router which can do that (MAP-E+global static IPv4+multiple port forwarding)?
Or could you suggest some router I can install OpenWRT and have this functionality?
Router needs to have 2 x 10GbE connections (WAN and LAN), as I plan to use 10GbE in local network. 

Would appreciate any thoughts/ideas

**Comment by advanpix** [comment]
Never mind. Japanese ISP do not use MAP-E in case of global static IPv4. Closing the issue.

**Comment by fakemanhk** [comment]
> Never mind. Japanese ISP do not use MAP-E in case of global static IPv4. Closing the issue.

Sorry for replying late, was in hospital for more than a week.
Yes you are right, static IPv4 assignment for dual stack is outside the domain of MAP-E since MAP-E is aimed at sharing same IPv4 among multiple users.

**Comment by advanpix** [comment]
Actually MAP-E supports static IPv4 just fine (RFC 7597). But ISP in Japan
don't use it for some reason.
