### ISSUE TITLE
request for SoftBank Hikari 10G support

### ISSUE THREAD

**Issue by missing233** [fakemanhk/openwrt-jp-ipoe#19]
XG-100NE router provided by SoftBank indicates that it uses the MAP-E tunnel to offer IPv4 address, and unfortunately, SoftBank does not offer PPPoE access.
 I tried setting it up on my OpenWRT router. WAN6 can obtain a /56 IPv6-PD, allowing LAN devices to access the IPv6 Internet. However, when using the online MAP-E rule calculator and entering the obtained IPv6 prefix 2400:2410:xxxx:xxxx::, the calculator says: '未対応のプレフィックス' 
Does anyone know how to calculate SoftBank's MAP-E parameters?

![20230812135535](https://github.com/fakemanhk/openwrt-jp-ipoe/assets/18642603/34f574e4-6c3b-457c-bc3a-328b12a3406b)
![20230812135547](https://github.com/fakemanhk/openwrt-jp-ipoe/assets/18642603/85d8131c-4b9f-47bc-a435-3c8c28804962)
![20230812135652](https://github.com/fakemanhk/openwrt-jp-ipoe/assets/18642603/d63c96b9-f663-4c04-923b-2713a4ca173c)

**Comment by fakemanhk** [comment]
I searched a bit about Softbank 10G with XG-100NE HGW, and found [this page](https://zenn.dev/zyun/scraps/d6d3781094804a) saying that it's actually using IPIP tunnel to achieve 4-to-6 which is not MAP-E. I don't know if you have any chance to do packet dump on WAN side for verification (the above mentioned page there was someone performed a dump and showing it's IPIP and unfortunately it's built-in HGW which currently no information can tell how to do the mapping yet)

**Comment by fakemanhk** [comment]
> The port mapping, I briefly explored Softbank's page and found that there doesn't seem to be a specified range of ports that can be forwarded

Some NTT providers with fixed IPv4 assignment do the same thing, but the main difference is NTT users can still use their own router to perform their own IPIP tunneling because the data for tunnel creation is already known, but Softbank one is still an unknown.

I will close this issue now since the MAP-E methodology here is unlikely to help in your case, Softbank/Nuro users apparently have no way to ditch the bundled router.

**Comment by fakemanhk** [comment]
Can you share a bit on how did you setup that one? In the past I didn't
find it and now a friend also using SoftBank is having trouble on the 1G
line.

**Comment by fakemanhk** [comment]
> Sorry for the late reply. After chatting with some folks, it seems NTT and Softbank are really particular about this matter, so I can't disclose specifics right now. I wrote a [blog post](https://blog.missing233.com/2023/08/13/softbank-hikari-research/) (in Chinese) about my research during this period. You might find some of the approaches there.

OK no problem, I think I know the method you did for the tunnel (my colleague did this on his OpenWrt 18.06 already) but it's just too troublesome to implement, I was thinking you know a more simple way to do this IPIP tunnel but apparently there is no way to make it simple.
