### ISSUE TITLE
GmoBB support: only ipv6 connectivity, ipv4 MAP rule is invalid

### ISSUE THREAD

**Issue by LIII-XXII** [fakemanhk/openwrt-jp-ipoe#22]
Hello, I followed this guide and get ipv6 connectivity with map-e, but there are some differences and ipv4 isn't working with map-e:
- the ip6prefix I get is `240b:xx:xxx:xxxx::/60` instead of `/64` which gives some errors on the online calculator
- if I use the calculator settings anyway, the wan6mape interface in OpenWRT gives me the `MAP rule is invalid` error.
- the ipv4 range that the calculator gives me looks valid (I get an address in that range if using the ISP-provided router)

Any tips? I'll check the reference and see if I can figure it out without the calculator.

**Comment by LIII-XXII** [comment]
If I understand well, I should probably set another 0 in the ip6prefix to have 64 bits fixed, I will try this later.

**Comment by LIII-XXII** [comment]
I'm pretty confident it is map-e, because:
- I get an ipv6 address via dhcp6 in openwrt
- the ipv4 address I get with the NTT router matches the one the online calculator gives me based on the ipv6 address
- the ports I can reach with the NTT router also match the port ranges that the map-e calculator gives

but I'm interested in trying that out, if just for troubleshooting / understanding what both routers do. Can you recommend some tools or some specific things to look for in the packet capture?

**Comment by LIII-XXII** [comment]
I retried this and can now get ipv6 connectivity, and an ipv4 with map-e, however I'm unable to connect to anything using on the internet using ipv4

**Comment by LIII-XXII** [comment]
I finally got it to work. The issue was that there are some differences in dhcp6, so relay mode didn't work. I'll post my /etc/config/network here for future reference if anybody is interested in using openwrt with GmoBB.

**Comment by LIII-XXII** [comment]
it's 1G, but I expect that the settings would be the same

**Comment by LIII-XXII** [comment]
here are my settings with the public IP details replaced with 1234567891 digits:

the WAN interface is eth1, LAN is eth0:

https://openwrt.org/toh/buffalo/wzr-hp-ag300h

![router](https://openwrt.org/_media/media/buffalo/wzr-hp-ag300h.png)


```
config interface 'loopback'
	option device 'lo'
	option proto 'static'
	option ipaddr '127.0.0.1'
	option netmask '255.0.0.0'

config globals 'globals'
	option ula_prefix 'fd13:1234:5678::/48'

config interface 'wan6'
	option device 'eth1'
	option proto 'dhcpv6'
	option reqaddress 'try'
	option reqprefix 'auto'

config device
	option name 'br-lan'
	option type 'bridge'
	list ports 'eth0.1'

config interface 'lan'
	option device 'br-lan'
	option proto 'static'
	option ipaddr '192.168.1.1'
	option netmask '255.255.255.0'
	option ip6assign '60'

config switch
	option name 'switch0'
	option reset '1'
	option enable_vlan '1'

config switch_vlan
	option device 'switch0'
	option vlan '1'
	option ports '1 2 3 4 0t'

config interface 'netmape'
	option proto 'map'
	option maptype 'map-e'
	option ipaddr '123.45.0.0'
	option ip4prefixlen '15'
	option ip6prefix '1234:50::'
	option ip6prefixlen '31'
	option ealen '25'
	option psidlen '8'
	option offset '4'
	option tunlink 'wan6'
	option mtu '1460'
	option legacymap '1'
	option encaplimit 'ignore'
	option peeraddr '1234:5600:789:100::64'
```

**Comment by fakemanhk** [comment]
> here are my settings with the public IP details replaced with 1234567891 digits:
> 
> the WAN interface is eth1, LAN is eth0:
> 
> https://openwrt.org/toh/buffalo/wzr-hp-ag300h
> 
> ![router](https://camo.githubusercontent.com/6b11a84dc1fdbcee0b8c279b80ddf6386f4b7aa55f396efde4c50b9ba9d24893/68747470733a2f2f6f70656e7772742e6f72672f5f6d656469612f6d656469612f62756666616c6f2f777a722d68702d6167333030682e706e67)
> 
> ```
> config interface 'loopback'
>     option device 'lo'
>     option proto 'static'
>     option ipaddr '127.0.0.1'
>     option netmask '255.0.0.0'
> 
> config globals 'globals'
>     option ula_prefix 'fd13:1234:5678::/48'
> 
> config interface 'wan6'
>     option device 'eth1'
>     option proto 'dhcpv6'
>     option reqaddress 'try'
>     option reqprefix 'auto'
> 
> config device
>     option name 'br-lan'
>     option type 'bridge'
>     list ports 'eth0.1'
> 
> config interface 'lan'
>     option device 'br-lan'
>     option proto 'static'
>     option ipaddr '192.168.1.1'
>     option netmask '255.255.255.0'
>     option ip6assign '60'
> 
> config switch
>     option name 'switch0'
>     option reset '1'
>     option enable_vlan '1'
> 
> config switch_vlan
>     option device 'switch0'
>     option vlan '1'
>     option ports '1 2 3 4 0t'
> 
> config interface 'netmape'
>     option proto 'map'
>     option maptype 'map-e'
>     option ipaddr '123.45.0.0'
>     option ip4prefixlen '15'
>     option ip6prefix '1234:50::'
>     option ip6prefixlen '31'
>     option ealen '25'
>     option psidlen '8'
>     option offset '4'
>     option tunlink 'wan6'
>     option mtu '1460'
>     option legacymap '1'
>     option encaplimit 'ignore'
>     option peeraddr '1234:5600:789:100::64'
> ```

Looks like you don't need to set a manual prefix on WAN6 interface when you are getting /60 from ISP? Anything else changed?

Also it's interesting that they are not giving you the /56 but /60, your plan comes with phone or not?

**Comment by LIII-XXII** [comment]
the wan6 part is pretty much stock from resetting the router. my plan comes with a phone. I did get /60 from the start (see the first post). it's not specified manually. I guess I _could_ set it in settings but I think the dhcp6 picks that up automatically from the isp here.

**Comment by fakemanhk** [comment]
OK then probably for those signed up phone service, router will be able to
get proper information for WAN interface, unlike mine, without phone
service I have to manually put in the 64 bit prefix to WAN6 interface to
make it work (it took me several months to figure out)

**Comment by LIII-XXII** [comment]
I'm going to set up an ethernet phone on top of openwrt and configure it for 光電話, I'll give some pointers if I get it to work

**Comment by missing233** [comment]
> I'm going to set up an ethernet (SIP?) phone on top of openwrt and configure it for 光電話, I'll give some pointers if I get it to work

I've been using SoftBank Hikari 10G (FLET'S CROSS) and managed to get a /56 prefix even without the Hikari Denwa service.
 Not entirely sure, but does FLET'S HIKARI use RJ11 or RJ45 for their Hikari Denwa? Seems like there aren’t any openwrt compatible routers with RJ11 ports.

**Comment by missing233** [comment]
> it's 1G, but I expect that the settings would be the same

It's a bit different. FLET'S NEXT 1G has a DHCPv6 lifetime of 30 days, while FLET'S CROSS 10G has a lifetime of just 4 hours. My odhcp6c always loses connection after 8 hours when running on FLET'S CROSS. 
I'm looking for someone else using FLET'S CROSS 10G to see if this is a common issue.

**Comment by LIII-XXII** [comment]
> does FLET'S HIKARI use RJ11 or RJ45 for their Hikari Denwa?
The NTT box uses RJ11, but SIP phones are RJ45 afaik, they run on the network... the OpenWRT side would probably use this package: https://openwrt.org/docs/guide-user/services/voip/asterisk
I'm actually interested in 10G, but afaik there is no Openwrt router that supports the speed, let me know if you have hardware to recommend

**Comment by missing233** [comment]
> The NTT box uses RJ11, but SIP phones are RJ45 afaik, they run on the network... the OpenWRT side would probably use this package: https://openwrt.org/docs/guide-user/services/voip/asterisk
> 
> > I'm looking for someone else using FLET'S CROSS 10G to see if this is a common issue.
> 
> I'm actually interested in 10G, but afaik there is no Openwrt router that supports the speed, let me know if you have hardware to recommend

From what I know, the Xiaomi 10000 router is the most affordable one running openwrt that comes with 1x 10GbE, 1x 10G SFP+, and 4x 2.5GbE. However, currently it can only unlock SSH and cannot run the full openwrt firmware; its official firmware only supports PPPoE. Additionally, a x86 server with X550T2 or X710DA2 is a good choice.

Regarding SIP phones, I noticed that the HGW has 2*RJ11 ports. Does this mean that Hikari Denwa requires RJ11? If so, it seems that there are no openwrt routers available for SIP phone.

**Comment by fakemanhk** [comment]
Puzzle IEI-M902 has 3 x 10GbE + 6 x 2.5GbE which already has official
OpenWrt support (no WiFi).

Currently I got the second hand Buffalo WXR-5950AX12 which has 2 x 10GbE
and will have 23.05 support soon.
