### ISSUE TITLE
Can't use the MAP-E rule calculator with IP starting with `2408`

### ISSUE THREAD

**Issue by Kuredant** [fakemanhk/openwrt-jp-ipoe#23]
Hi,

Thanks for the detailed instructions on how to setup IPv6 on OpenWrt with NTT.
I have an issue when trying to use the [online MAP-E rule calculator](http://ipv4.web.fc2.com/map-e.html) to figure out the settings for the MAP-E interface.

My plan is _So-net 光 with フレッツ S_ and my wan6 interface is getting an IP that looks like `2408:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx/64`.  
When inputting the prefix in the MAP-E rule calculator (`2408:xxxx:xxxx:xxxx::`), I'm getting an "unsupported prefix" error ("未対応のプレフィックス").

Does this mean I'm not able to set up MAP-E, or is there something wrong with the website?

**Comment by fakemanhk** [comment]
First, are you sure SONET is using MAP-E? This guide is only for ISP using MAP-E, but you can't force it into MAP-E operation mode if ISP doesn't use it. And I remember SONET is using ONT + router combo already? (Which means IPv4 from your SONET device is already in form of 192.168.x.x)

**Comment by Kuredant** [comment]
> And I remember SONET is using ONT + router combo already? (Which means IPv4 from your SONET device is already in form of 192.168.x.x)

I'm already connected to NTT's network via PPPoE, I'm just trying to set up IPoE.

> First, are you sure SONET is using MAP-E? This guide is only for ISP using MAP-E, but you can't force it into MAP-E operation mode if ISP doesn't use it.

Yes, I'm using So-net via NTT's Flet's Hikari network. Just like NTT ぷらら, it's using MAP-E.

It turns out the issue was that I had to manually subscribe to v6プラス (i.e. IPoE) through this link: https://www.so-net.ne.jp/access/hikari/v6plus/
After a few hours, I was able to get an IPv6 from the ISP compatible with http://ipv4.web.fc2.com/map-e.html.
Following your guide, I was able to smoothly setup MAP-E with my OpenWrt router.
Thanks for this very thorough guide!

**Comment by fakemanhk** [comment]
> It turns out the issue was that I had to manually subscribe to v6プラス (i.e. IPoE) through this link: https://www.so-net.ne.jp/access/hikari/v6plus/  
> After a few hours, I was able to get an IPv6 from the ISP compatible with http://ipv4.web.fc2.com/map-e.html.  
> Following your guide, I was able to smoothly setup MAP-E with my OpenWrt router.

Oh I see, in fact my ぷらら has the same setting when I use their 1G fiber plan, by default you can only use PPPoE IPv4, though you can get a v6 address from it but it will be on a wrong network (without MAP-E), glad that this works for you!
