### ISSUE TITLE
request for SoftBank Hikari 1G support

### ISSUE THREAD

**Issue by falood** [fakemanhk/openwrt-jp-ipoe#24]
thanks a lot for the note ❤️ 
similar with #19, I also got issue with softbank hikari when calculate the MAP-E with an ipv6 address starts with 2400:2650:*
the plan is ファミリー・スーパーハイスピード which should be the 1Gb one, I'm not sure whether MAP-E or IPIP is in use.
I'm trying to create a ipip6 tunnel, but I'm still be asked for the `Tunnel remote IPv6 address` which I don't know how to get.
any idea about my case? thanks

**Comment by fakemanhk** [comment]
Softbank is not easy to do, and you also need to do packet dump to get some credential from WAN side

**Comment by falood** [comment]
thanks for your response, I found the page https://blog.missing233.com/2023/09/16/softbank-hikari-openwrt-configuration/ which explain the details about the packet dump.
but I don't have a switch support mirror ports right now 🙈 will buy one and give it a try
