### ISSUE TITLE
My device only have iptables , how can i make it work?

### ISSUE THREAD

**Issue by duzefu** [fakemanhk/openwrt-jp-ipoe#31]
My device only have iptables instead of nft . And the nft rules looks so complex , I can't convert it to iptables rules by using CHATGPT? Can anyone tell me how to do ?

**Comment by fakemanhk** [comment]
I believe there won't be a version for iptables as it's legacy.

**Comment by duzefu** [comment]
> I believe there won't be a version for iptables as it's legacy.我相信 iptables 不会有一个版本，因为它是遗留的。

anyway ,thank you
