### ISSUE TITLE
[Nuro Hikari] IPv4 can't receive data package.

### ISSUE THREAD

**Issue by EYW-015** [fakemanhk/openwrt-jp-ipoe#34]
I'm using Nuro Hikari 2G, and it's on MAP-E mode. I've succeeded to configure the map-e interface and get the correct ipv4 address the same as nuro modem.
But the ipv4 can't receive any data package.

I've tried to replace the `map.sh` file but not work.
Seems like others were only truble in modem authenticate or MAP-E configure.

The main issue https://github.com/meh301/HG8045Q/issues/2
MAP-E configure https://github.com/herrkartoffel/openwrt-jp-map-e-nuro
Auto script https://github.com/site-u2023/config-software/blob/main/map-e-nuro.sh
The modified `map.sh` from yours https://github.com/site-u2023/map-e

If you don't know about Nuro Hikari, just close this issue.
Thank you.

![image](https://github.com/user-attachments/assets/80abecb2-c206-48e3-acf7-37884773ddcf)

**Comment by LIII-XXII** [comment]
I think the `wan` interface is not needed. (I also think it should be in the same firewall zone, by the way!). Try these (in order of difficulty).
`wan` is needed if you have an IP phone (NURO does not offer 光電話 AFAIK, so you don't need it). It is also not getting an IP address via DHCP4, which it would be getting if you had 光電話. **You do not need `wan`.**

- removing `wan` from default route (i.e. uncheck "Use default gateway" from the `wan` interface)
- deleting `wan`
- resetting the router config, deleting `wan`, setting up map-e from scratch

**Comment by LIII-XXII** [comment]
By the way, you did not specify, I assume ipv6 works as expected, does it?

**Comment by EYW-015** [comment]
> By the way, you did not specify, I assume ipv6 works as expected, does it?

Yes, ipv6 works fine.

I've tried delete the wan interface and reset the map interface. But ipv4 still can't receive any package.

**Comment by fakemanhk** [comment]
@EYW-015 Did you find the way to fix the problem?

**Comment by EYW-015** [comment]
@fakemanhk 
Yes, I bought a new PON Stick and it worked. Some one said the VSOL-V2802RH firmware will block MAP-E traffic.
https://github.com/meh301/HG8045Q/issues/2#issuecomment-2329593416
