### ISSUE TITLE
IPv4 PING doesn't work

### ISSUE THREAD

**Issue by fakemanhk** [fakemanhk/openwrt-jp-ipoe#5]
After setup, I found that there is no respond when I ping IPv4 address (doesn't work even on router itself), IPv6 ping is working as expected (both client & router).

**Comment by cmspam** [comment]
The reason is because fw4 somehow doesn't let the map.sh script to forward icmp to ports.
We can directly add these forwards into the map.sh file to fix it.

**Comment by fakemanhk** [comment]
Duplicate of #8
